### ISSUE TITLE
Réparer les tests unitaires de téléservice Loiret

### ISSUE THREAD

**Issue by guillett** [betagouv/mes-aides-ui#963]
Je sépare un sujet des problèmes d'installation (https://github.com/betagouv/mes-aides-ui/issues/924). Merci beaucoup @StephaneColson !

### Tests unitaires en erreur
Enfin 3 tests unitaires échouent sur ma machine:

```
   1) Loiret Teleservice returns expected values for internal purpose:
      Error: Expected [ { label: 'votre date de naissance', formattedValue: '6 juin 1983' }, { label: 'votre situation familiale', formattedValue: 'En union libre' }, { label: 'vos salaires (net) sur les 12 derniers mois', formattedValue: '27 400,00 €' }, { label: 'votre retraite (net) sur les 12 derniers mois', formattedValue: '1 200,00 €' }, { label: 'vos allocations sur les 12 derniers mois', formattedValue: '2 400,00 €' }, { label: 'vos pensions alimentaires perçues', formattedValue: '0,00 €' }, { label: 'vos revenus locatifs', formattedValue: '0,00 €' }, { label: 'vos revenus du capital', formattedValue: '0,00 €' } ] to include { label: 'votre date de naissance', formattedValue: '5 juin 1983' }
       at assert (node_modules/expect/lib/assert.js:29:9)
       at Expectation.toInclude (node_modules/expect/lib/Expectation.js:215:28)
       at Context.<anonymous> (test/backend/teleservices/loiret.js:86:27)
 
   2) Loiret Teleservice returns expected values for date de naissance:
 
       Error: Expected '06/06/1983' to equal '05/06/1983'
       + expected - actual
 
       -06/06/1983
       +05/06/1983
       
       at assert (node_modules/expect/lib/assert.js:29:9)
       at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
       at Context.<anonymous> (test/backend/teleservices/loiret.js:100:46)
 
   3) Loiret Teleservice returns expected values for date de naissance:
 
       Error: Expected '06/06/1983' to equal '05/06/1983'
       + expected - actual
 
       -06/06/1983
       +05/06/1983
       
       at assert (node_modules/expect/lib/assert.js:29:9)
       at Expectation.toEqual (node_modules/expect/lib/Expectation.js:81:30)
       at Context.<anonymous> (test/backend/teleservices/loiret.js:139:46)
```

**Comment by guillett** [comment]
@ManonLger as-tu le problème sur ta machine ? :)

**Comment by ManonLger** [comment]
@guillett Oui !
